# Generated by Django 3.1.1 on 2020-09-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='Like',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='Like_Num',
            field=models.IntegerField(default=0),
        ),
    ]
