# Generated by Django 3.1.1 on 2020-09-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200914_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='photo',
        ),
    ]
