# Generated by Django 3.1.1 on 2020-09-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_feedcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
