# Generated by Django 3.1.1 on 2020-09-14 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_feed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='Image',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.feed')),
            ],
        ),
    ]
